@inject('images', 'App\Services\BlogImages')
@extends('layouts.app')
@section('title',($post->exists?'Edit post':'New post').' — Artificially Curious')
@section('content')<section class="admin"><a class="text-link" href="{{ route('admin.posts.index') }}">← All posts</a><div class="section-heading"><div><div class="eyebrow">EDITOR’S DESK</div><h1>{{ $post->exists?'Shape your story':'Start something curious' }}<span class="mint">.</span></h1></div><span class="badge">{{ $post->is_published?'Published / scheduled':'Draft' }}</span></div>
<form method="post" enctype="multipart/form-data" action="{{ $post->exists?route('admin.posts.update',$post):route('admin.posts.store') }}" class="editor-form" id="post-form">@csrf @if($post->exists) @method('PUT') @endif
<div class="editor-main"><div class="panel"><label for="title">Post title</label><input class="title-input" id="title" name="title" value="{{ old('title',$post->title) }}" placeholder="An idea worth exploring…" maxlength="255" required><label for="body">The story</label><textarea id="body" name="body" data-editor data-upload-url="{{ route('admin.images.store') }}">{{ old('body',$post->body) }}</textarea><small id="editor-status" role="status">Rich text editor loading…</small></div>
<div class="panel"><label for="seo_summary">SEO summary</label><textarea id="seo_summary" name="seo_summary" rows="3" maxlength="255" required>{{ old('seo_summary',$post->seo_summary) }}</textarea><small><span id="summary-count">0</span>/255 characters · A short description for readers and search engines.</small></div></div>
<aside class="editor-side"><div class="panel"><h2>Publication</h2><label for="post_date">Post date (dd/mm/yyyy)</label><input id="post_date" name="post_date" value="{{ old('post_date',$post->post_date?->format('d/m/Y')??today()->format('d/m/Y')) }}" placeholder="dd/mm/yyyy" pattern="[0-9]{2}/[0-9]{2}/[0-9]{4}" required><small>Future dates go live on that date after publishing.</small><label class="toggle"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured',session()->hasOldInput()?false:$post->is_featured))><span><strong>Featured</strong><small>Highlight this post on the homepage.</small></span></label><label class="toggle"><input type="checkbox" name="is_subscriber" value="1" @checked(old('is_subscriber',session()->hasOldInput()?false:$post->is_subscriber))><span><strong>Subscriber only</strong><small>Show a short preview until readers log in.</small></span></label>@if($post->exists)<a class="button secondary full" href="{{ route('admin.posts.preview', $post) }}" target="_blank" rel="noopener">Preview saved post ↗</a>@endif<button class="button full" type="submit" name="action" value="publish">{{ $post->is_published?'Save & publish':'Publish post' }} ↗</button><button class="button secondary full" type="submit" name="action" value="draft">{{ $post->is_published?'Unpublish & save draft':'Save draft' }}</button></div>
<div class="panel"><h2>Organise</h2><label for="tags">Tags</label><input id="tags" name="tags" value="{{ old('tags',implode(', ',$post->tags??[])) }}" maxlength="500" placeholder="AI, creativity, research"><small>Separate tags with commas.</small></div>
<div class="panel"><h2>Cover image</h2>@if($post->image)<img class="cover-preview" src="{{ $images->url($post->image, 'thumbnail') }}" alt="Current cover">@endif<label for="image">{{ $post->image?'Replace image':'Upload image' }}</label><input type="file" id="image" name="image" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG or WebP. Up to 8 MB and 6000 × 6000 px. Original kept, with thumbnail, small and large copies generated automatically.</small><img id="image-preview" class="cover-preview" alt="Selected cover preview" hidden></div></aside></form></section>@endsection
