@inject('images', 'App\Services\BlogImages')
@extends('layouts.app')
@section('content')
<section class="hero"><div class="hero-copy"><div class="eyebrow"><span class="status-dot"></span> AN INDEPENDENT JOURNAL ON AI</div><h1>A little artificial.<br>A lot of <em>curiosity.</em></h1><p>Making sense of a world thinking differently.<br>Ideas, experiments and honest perspectives on AI.</p><a class="button" href="#journal">Explore the journal <span>↓</span></a><div class="hero-note"><span>01 —</span> For humans who ask what’s next.</div></div><x-art/></section>
<div class="ticker"><span>BEYOND THE HYPE</span><span>✳</span><span>IDEAS WORTH EXPLORING</span><span>✳</span><span>HUMAN PERSPECTIVES</span><span>✳</span><span>ARTIFICIAL INTELLIGENCE</span></div>
@if($featured)<section class="featured"><div class="featured-visual">@if($featured->image)<img src="{{ $images->url($featured->image, 'small') }}" alt="{{ $featured->title }}">@else<x-art/>@endif</div><div class="featured-copy"><div class="eyebrow">✳ IN THE SPOTLIGHT</div><div class="card-meta">@foreach($featured->tags ?? [] as $tag)<a href="{{ route('home',['tag'=>$tag]) }}#journal">{{ $tag }}</a>@endforeach<time datetime="{{ $featured->post_date->toDateString() }}">{{ $featured->post_date->format('d/m/Y') }}</time><span>{{ $featured->reading_time_minutes }} min read</span></div><h2><a href="{{ route('posts.show',$featured->slug) }}">{{ $featured->title }}</a></h2><p>{{ $featured->seo_summary }}</p><a class="text-link" href="{{ route('posts.show',$featured->slug) }}">Explore this story ↗</a></div></section>@endif
<section id="journal" class="journal"><div class="section-heading"><div><div class="eyebrow">THE JOURNAL</div><h2>Fresh perspectives<span class="mint">.</span></h2></div><span class="muted">A space to question, learn & discover.</span></div>
<div class="filter-bar"><div class="tag-links"><a class="{{ !request('tag')?'active':'' }}" href="{{ route('home') }}#journal">All stories</a>@foreach($popularTags as $tag)<a class="{{ request('tag')===$tag?'active':'' }}" href="{{ route('home',['tag'=>$tag]) }}#journal">{{ $tag }}</a>@endforeach</div><form method="get" action="{{ route('home') }}#journal" class="search"><label class="sr-only" for="q">Search stories</label><input id="q" name="q" value="{{ request('q') }}" placeholder="Search the journal…">@if(request('tag'))<input type="hidden" name="tag" value="{{ request('tag') }}">@endif<button aria-label="Search">↗</button></form></div>
@if(request('tag'))<p class="muted">Tagged: {{ request('tag') }} · <a href="{{ route('home') }}#journal">Clear filter</a></p>@endif
<div class="post-grid">@forelse($posts as $post)<x-post-card :post="$post"/>@empty<div class="empty-state"><span class="mint large-symbol">✳</span><h3>{{ request()->hasAny(['q','tag'])?'No stories found.':'Good questions start here.' }}</h3><p>{{ request()->hasAny(['q','tag'])?'Try another search or explore all stories.':'The journal is just getting started. New ideas are on their way.' }}</p>@can('admin')<a class="button" href="{{ route('admin.posts.create') }}">Write your first story ↗</a>@else<a class="text-link" href="{{ route('home') }}">Explore all stories ↗</a>@endcan</div>@endforelse</div><div class="pagination">{{ $posts->links() }}</div></section>
@guest<section class="join-banner"><div><div class="eyebrow">CURIOSITY LOVES COMPANY</div><h2>There’s more to the story.</h2><p>Create a free account to read every members-only article.</p></div><a class="button" href="{{ route('register') }}">Join the curious <span>↗</span></a></section>@endguest
@endsection
