@inject('images', 'App\Services\BlogImages')
@inject('authorImages', 'App\Services\AuthorImages')
@extends('layouts.app')
@section('title', $post->title.' — Artificially Curious')
@section('description', $post->seo_summary)
@section('content')
<article class="article">@if($preview)<div class="panel"><div class="eyebrow">DRAFT PREVIEW</div><p>This is how the saved post will look. It is not visible to the public.</p><a class="text-link" href="{{ route('admin.posts.edit', $post) }}">← Continue editing</a></div>@else<a class="text-link" href="{{ route('home') }}#journal">← Back to the journal</a>@endif<header class="article-header"><div class="eyebrow">@foreach($post->tags ?? [] as $tag)<a href="{{ route('home',['tag'=>$tag]) }}#journal">{{ $tag }}</a>@endforeach @if($post->is_subscriber) · MEMBERS ONLY @endif</div><h1>{{ $post->title }}</h1><p class="standfirst">{{ $post->seo_summary }}</p><div class="card-meta"><time datetime="{{ $post->post_date->toDateString() }}">{{ $post->post_date->format('d/m/Y') }}</time><span class="meta-separator" aria-hidden="true"></span><span>{{ $post->reading_time_minutes }} min read</span>@if(!empty($post->tags))<span class="meta-separator" aria-hidden="true"></span>@foreach($post->tags as $tag)<a href="{{ route('home',['tag'=>$tag]) }}#journal">#{{ $tag }}</a>@endforeach @endif</div></header>
@if($post->image)<img class="article-cover" src="{{ $images->url($post->image, 'large') }}" alt="{{ $post->title }}">@endif
@if($postContents['headings'])<nav class="table-of-contents" aria-label="Table of contents"><details><summary class="contents-toggle"><span class="eyebrow">IN THIS ARTICLE</span><span class="contents-chevron" aria-hidden="true"></span></summary><ol>@foreach($postContents['headings'] as $heading)<li><a href="#{{ $heading['id'] }}">{{ $heading['label'] }}</a></li>@endforeach</ol></details></nav>@endif
<div class="article-body">@if($locked)<p>{{ Str::limit(html_entity_decode(strip_tags($post->body)), min(350, (int) floor(mb_strlen(html_entity_decode(strip_tags($post->body))) * .2))) }}</p><div class="paywall"><div class="eyebrow">KEEP YOUR CURIOSITY GOING</div><h2>The rest is for our readers.</h2><p>This story is currently available to existing readers.</p><a class="button" href="{{ route('login') }}">Log in to continue ↗</a></div>@else{!! $postContents['html'] !!}@endif
<div class="tags">@foreach($post->tags??[] as $tag)<a href="{{ route('home',['tag'=>$tag]) }}#journal">#{{ $tag }}</a>@endforeach</div></div>
<aside class="share-box" aria-label="Share this article"><div class="eyebrow">SHARE THIS ARTICLE</div><div class="share-links"><a href="{{ $shareLinks['x'] }}" target="_blank" rel="noopener noreferrer" aria-label="Share {{ $post->title }} on X">X <span aria-hidden="true">↗</span></a><a href="{{ $shareLinks['facebook'] }}" target="_blank" rel="noopener noreferrer" aria-label="Share {{ $post->title }} on Facebook">Facebook <span aria-hidden="true">↗</span></a><a href="{{ $shareLinks['linkedin'] }}" target="_blank" rel="noopener noreferrer" aria-label="Share {{ $post->title }} on LinkedIn">LinkedIn <span aria-hidden="true">↗</span></a></div></aside>
@if(!$locked && $author && ($author->name || $author->bio || $author->image))<aside class="author-box" aria-label="About the author">@if($author->image)<img src="{{ $authorImages->url($author->image) }}" alt="{{ $author->name }}">@endif<div><div class="eyebrow">ABOUT THE AUTHOR</div>@if($author->name)<h2>{{ $author->name }}</h2>@endif @if($author->bio)<p>{{ $author->bio }}</p>@endif @if($author->x_url || $author->facebook_url || $author->linkedin_url)<div class="author-social-links">@if($author->x_url)<a href="{{ $author->x_url }}" target="_blank" rel="me noopener noreferrer">X <span aria-hidden="true">↗</span></a>@endif @if($author->facebook_url)<a href="{{ $author->facebook_url }}" target="_blank" rel="me noopener noreferrer">Facebook <span aria-hidden="true">↗</span></a>@endif @if($author->linkedin_url)<a href="{{ $author->linkedin_url }}" target="_blank" rel="me noopener noreferrer">LinkedIn <span aria-hidden="true">↗</span></a>@endif</div>@endif</div></aside>@endif</article>
@endsection
